
[functions.recommendations-list]
enabled = true
verify_jwt = true
import_map = "./functions/recommendations-list/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/recommendations-list/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/recommendations-list/*.html" ]

[functions.recommendations-submit]
enabled = true
verify_jwt = true
import_map = "./functions/recommendations-submit/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/recommendations-submit/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/recommendations-submit/*.html" ]

[functions.recommendations-metrics]
enabled = true
verify_jwt = true
import_map = "./functions/recommendations-metrics/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/recommendations-metrics/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/recommendations-metrics/*.html" ]
